include $(GNUSTEP_MAKEFILES)/common.make

LIBRARY_NAME = libGSINI
# libGSINI_OBJC_FILES = INISerialization.m
libGSINI_C_FILES = ini.c
libGSINI_HEADER_FILES = ini.h
# INISerialization.h
libGSINI_HEADER_FILES_INSTALL_DIR = GSINI


include $(GNUSTEP_MAKEFILES)/library.make