include $(GNUSTEP_MAKEFILES)/common.make

PACKAGE_NAME = GSBreeze
BUNDLE_NAME = GSBreeze
BUNDLE_EXTENSION = .theme
VERSION = 1

GSBreeze_PRINCIPAL_CLASS = GSBBreezeTheme
GSBreeze_INSTALL_DIR = $(GNUSTEP_LIBRARY)/Themes
GSBreeze_RESOURCE_FILES = \
	Resources/breeze_icon_48.png
GSBreeze_OBJC_FILES = \
	GSBBreezeTheme.m
GSBreeze_OBJC_LIBS = -lGSINI

include $(GNUSTEP_MAKEFILES)/bundle.make
